name: "Build dan Deploy Chirpy"

on:
  push:
    branches: [main, master]
    paths-ignore: [.gitignore, README.md, LICENSE]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # 1. Checkout kode
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive  # Penting untuk assets Chirpy

      # 2. Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2  # HARUS 3.1.2
          bundler-cache: true

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # 4. Build situs
      - name: Build site
        run: bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production

      # 5. Verifikasi
      - name: Verify site
        run: |
          bundle exec htmlproofer _site \
            --disable-external \
            --check-html \
            --allow_hash_href \
            --ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

      # 6. Upload hasil build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
